### PR TITLE
Kubectl subcommand

### LINKED ISSUE #291: Suggestion: Stage kubectl to the /var/lib/k0s/pki
Now we have kubeconfig staged as /var/lib/mke/pki/admin.conf

If we would stage kubectl binary there as well, the bootstrap process would be even easier (now the end user either should already have kubctl installed or install it manually) and the cluster could be used right after mke worker joined.

### PR DESCRIPTION
**Pull request by jnummelin**
**Issue**
Fixes #291 

**What this PR Includes**
This PR adds `k0s kubectl` subcommand that handles the full kubectl functionality.

Had to wire up the `-l` logging flags differently as kubectl also has `-l` for label selectors. Now k0s `-l` is wired directly only for server/worker commands

```
/ # ./k0s kubectl get node -o wide
NAME   STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
k0s    Ready    <none>   86d   v1.19.3   172.17.0.2    <none>        Alpine Linux v3.12   4.15.0-1060-aws   containerd://1.4.0
/ # ./k0s kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-gj2gv   1/1     Running   0          86d
kube-system   calico-node-plsng                          1/1     Running   0          86d
kube-system   coredns-5c98d7d4d8-qnblr                   1/1     Running   0          86d
kube-system   konnectivity-agent-z88fn                   1/1     Running   0          86d
kube-system   kube-proxy-rp2dp                           1/1     Running   0          86d
kube-system   metrics-server-7d4bcb75dd-pq2zl            1/1     Running   0          86d
```

### CODE REVIEW

**Comment by kat33rd** [comment]
[]()

**Review by jasmingacic — DISMISSED** [review]
Tested it. Works like a charm.

A side note. Perhaps, if possible, abbreviating `k0s kubectl ...` with an alias `k0s ctl ...` could make it more convenient.

**Comment by kat33rd** [comment]
[]()

**Comment by kke** [comment]
> Tested it. Works like a charm.
> 
> A side note. Perhaps, if possible, abbreviating `k0s kubectl ...` with an alias `k0s ctl ...` could make it more convenient.

Maybe not `k0s ctl` due to `k0sctl`, maybe `k0s kc`.

**Comment by jasmingacic** [comment]
Closes #291

**Review by kke — DISMISSED** [review]

**Comment by jnummelin** [comment]
> Maybe not k0s ctl due to k0sctl, maybe k0s kc.

Added alias `k0s kc`

**Review by jasmingacic — APPROVED** [review]

**Review by jasmingacic — APPROVED** [review]

**Review by jasmingacic — APPROVED** [review]

**Pull request merged**
