### PR TITLE
Rename mke.service to k0s.service

### PR DESCRIPTION
**Pull request by webwurst**
Reference to this service was renamed in Dockerfile

---
name: Pull Request
about: Create a Pull Request
title: ''
labels: ''
assignees: ''

---

**Issue**
Fixes #{ issue number }

**What this PR Includes**
A short description of what this PR does.

### CODE REVIEW

**Comment by jnummelin** [comment]
@webwurst Thanks for the PR. Could you sign the commit so DCO gets happy. :)

**Review by jasmingacic — APPROVED** [review]

**Review by ncopa — CHANGES_REQUESTED** [review]
Good catch! thanks!

Can you please update the commit message to include the [signed off line](https://github.com/k0sproject/k0s/pull/400/checks?check_run_id=1401069603)?

**Comment by jnummelin** [comment]
@webwurst maybe at same time you could rename the `mke.yaml` --> `k0s.yaml` in the same folder, it's kinda related.

**Comment by webwurst** [comment]
Is it good now? I am a bit of a git n00b ;)

**Review by jasmingacic — APPROVED** [review]

**Comment by jnummelin** [comment]
Thank you for the contribution @webwurst 🎉

**Pull request merged**
