### PR TITLE
Notify slack channel on job execution

### PR DESCRIPTION
**Pull request by trawler**
Signed-off-by: Karen Almog <kalmog@mirantis.com>

**What this PR Includes**
Send a notification on Slack on job execution.

### CODE REVIEW

**Review by kittiphophum18 — DISMISSED** [review]

**Comment by kke** [comment]
The message it generates is rather lengthy.

**Comment by trawler** [comment]
> The message it generates is rather lengthy.

Valid point... I'm still playing with the format though. But I also suppose that since this check is only triggered once a day, it should be too spammy.

**Comment by trawler** [comment]
slack message now shortened to include only:
```
workflow,ref,commit,author,job,took
```

**Comment by kke** [comment]
Didn't change noticeably.  In my opinion it could pretty much be an oneliner like:

```
New PR by Foo: Insert foo into foofoo
```

```
PR Approved by Bar: Insert foo into foofoo
```

```
New issue: Foo doesn't work
```

```
PR Merged: Insert foo into foofoo
```

```
Issue closed: Foo doesn't work
```


 Now it creates this huge hunk of text that covers the same area as some 20 lines of regular discussion.

**Comment by trawler** [comment]
> Didn't change noticeably. In my opinion it could pretty much be an oneliner like:
**_Before_**
Screenshot 2021-05-27 at 15 00 44

**_After_**
Screenshot 2021-05-27 at 15 01 03

**Review by jnummelin — APPROVED** [review]
LGTM

We can always tweak the format if it proves to be too spammy

**Review by kittiphophum18 — APPROVED** [review]

**Comment by kittiphophum18** [comment]
> Signed-off-by: Karen Almog <kalmog@mirantis.com>
> 
> 
> 
> **What this PR Includes**
> 
> Send a notification on Slack on job execution.

**Pull request merged**
