### PR TITLE
Drop unused calico containers

### LINKED ISSUE #649: Drop "unused" Calico init containers
**Is your feature request related to a problem? Please describe.**
Calico manifests have two "unused" init containers: upgrade-ipam and flex-vol driver dropper.

We do not really need the ipam upgrade init container at all since we've never used the old host-local ipam.

The flexvol driver is actually not used directly either, it's only for cases where there's e.g. Istio bundled too. Which we do not do in k0s at all.

Although these are only init container and do not consume any resources runtime, we could still drop these to simplify things.

**Describe the solution you'd like**
Drop the unused bits from calico manifests

### PR DESCRIPTION
**Pull request by jakolehm**
**Issue**
Fixes #649

### CODE REVIEW

**Review by jasmingacic — APPROVED** [review]

**Comment by jasmingacic** [comment]
@jakolehm  I guess the change causes the test below to fail:

```
--- FAIL: TestCalicoManifests (0.15s)
    --- FAIL: TestCalicoManifests/flex_volume_driver_path_set_from_config (0.03s)
        calico_test.go:129: 
            	Error Trace:	calico_test.go:129
            	Error:      	Should be true
            	Test:       	TestCalicoManifests/flex_volume_driver_path_set_from_config
            	Messages:   	Must have flexvol-driver-host volume
    --- FAIL: TestCalicoManifests/flex_volume_driver_path_set_from_default (0.02s)
        calico_test.go:153: 
            	Error Trace:	calico_test.go:153
            	Error:      	Should be true
            	Test:       	TestCalicoManifests/flex_volume_driver_path_set_from_default
            	Messages:   	Must have flexvol-driver-host volume
```

**Review by jasmingacic — DISMISSED** [review]
Tests are not passing

**Comment by ncopa** [comment]
I think we need to remove the tests that depends on the removed `flexvol-driver-host`
```diff
diff --git a/pkg/component/server/calico_test.go b/pkg/component/server/calico_test.go
index 1675197..b36132e 100644
--- a/pkg/component/server/calico_test.go
+++ b/pkg/component/server/calico_test.go
@@ -103,55 +103,6 @@ func TestCalicoManifests(t *testing.T) {
                }
                require.False(t, found, "Must not have FELIX_WIREGUARDENABLED env setting if config spec has no wireguard enabled")
        })
-
-       t.Run("flex_volume_driver_path_set_from_config", func(t *testing.T) {
-               cfg := v1beta1.DefaultClusterConfig()
-               cfg.Spec.Network.Calico.FlexVolumeDriverPath = "/etc/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds"
-               saver := inMemorySaver{}
-               crdSaver := inMemorySaver{}
-               calico, err := NewCalico(cfg, crdSaver, saver)
-               require.NoError(t, err)
-
-               _ = calico.processConfigChanges(calicoConfig{})
-
-               daemonSetManifestRaw, foundRaw := saver["calico-DaemonSet-calico-node.yaml"]
-               require.True(t, foundRaw, "must have daemon set for calico")
-               spec := daemonSetContainersEnv{}
-               require.NoError(t, yaml.Unmarshal(daemonSetManifestRaw, &spec))
-               found := false
-               for _, volume := range spec.Spec.Template.Spec.Volumes {
-                       if volume.Name != "flexvol-driver-host" {
-                               continue
-                       }
-                       found = true
-                       require.Equal(t, "/etc/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds", volume.HostPath.Path)
-               }
-               require.True(t, found, "Must have flexvol-driver-host volume")
-       })
-
-       t.Run("flex_volume_driver_path_set_from_default", func(t *testing.T) {
-               cfg := v1beta1.DefaultClusterConfig()
-               saver := inMemorySaver{}
-               crdSaver := inMemorySaver{}
-               calico, err := NewCalico(cfg, crdSaver, saver)
-               require.NoError(t, err)
-
-               _ = calico.processConfigChanges(calicoConfig{})
-
-               daemonSetManifestRaw, foundRaw := saver["calico-DaemonSet-calico-node.yaml"]
-               require.True(t, foundRaw, "must have daemon set for calico")
-               spec := daemonSetContainersEnv{}
-               require.NoError(t, yaml.Unmarshal(daemonSetManifestRaw, &spec))
-               found := false
-               for _, volume := range spec.Spec.Template.Spec.Volumes {
-                       if volume.Name != "flexvol-driver-host" {
-                               continue
-                       }
-                       found = true
-                       require.Equal(t, "/usr/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds", volume.HostPath.Path)
-               }
-               require.True(t, found, "Must have flexvol-driver-host volume")
-       })
 }
 
 // this structure is needed only for unit tests and basocally it describes some fields that are needed to be parsed out of the daemon set manifest
```

**Review by ncopa — CHANGES_REQUESTED** [review]
Remove the unit tests for the removed conainters

**Review by ncopa — APPROVED** [review]

**Review by jnummelin — APPROVED** [review]

**Pull request merged**
