### PR TITLE
chore: make helm timeout backward compatible

### PR DESCRIPTION
**Pull request by ricardomaraschini**
## Description

in the past the helm chart install timeout was moved from an integer to a string. this commit brings back the capability of using integers to set the helm chart timeout.

## Type of change

- [x] Chore
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by twz123** [comment]
Breaking the API was a [deliberate decision](https://github.com/k0sproject/k0s/issues/4172#issuecomment-2074568627) back in the day. Maybe the old assessment is no longer valid?

**Comment by ricardomaraschini** [comment]
> Breaking the API was a [deliberate decision](https://github.com/k0sproject/k0s/issues/4172#issuecomment-2074568627) back in the day. Maybe the old assessment is no longer valid?

We have been using the old API (timeout as integers) to allow users to set up timeouts for their helm charts. This breaking change without a correspondent CRD version change really broke our legs :-( I was trying to see how hard it would be to make this work with both integers and strings but it seems more complex than I anticipated.

**Comment by ricardomaraschini** [comment]
@twz123 Now that this is green would we consider reverting that incompatible change ?

**Comment by jnummelin** [comment]
@ricardomaraschini Would this unblock something for you guys? Like @twz123 said, it was a deliberate decision to break the API because the previous one was kinda broken.

**Comment by ricardomaraschini** [comment]
> @ricardomaraschini Would this unblock something for you guys? Like @twz123 said, it was a deliberate decision to break the API because the previous one was kinda broken.

Yes, this unblocks us to upgrade beyond v1.29. We are stuck on that version until we figure this out.

**Review by jnummelin — APPROVED** [review]

**Pull request merged**
