### PR TITLE
Bump k0sctl used in tests to v0.17.2

### PR DESCRIPTION
**Pull request by kke**
## Description

Bumps k0sctl in tests to 0.17.2.

There should be a better way than modifying so many files. 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [ ] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by twz123** [comment]
> There should be a better way than modifying so many files.

We could do something similar as for the other tool versions. But this makes things more complex (additional script invocations, use of placeholders) , and some places will need custom care anyways (e.g. go.mod, go.sum). Not sure if that holds its weight compared to some simple/stupid regex-replace. Probably depends on how often a bump happens. Ideally, some tool could do a fully automated PR. Dependabot cannot do this. Maybe Renovate could do it. But again, this would require quite some plumbing.

**Review by twz123 — APPROVED** [review]

**Comment by kke** [comment]
`cd hack/tool; go list -m -f '{{.Version}}' github.com/k0sproject/k0sctl` would give the version from go.mod. The rest could somehow get it from there.

**Comment by twz123** [comment]
> `cd hack/tool; go list -m -f '{{.Version}}' github.com/k0sproject/k0sctl` would give the version from go.mod. The rest could somehow get it from there.

That would require a go toolchain just to figure out the k0sctl version number. Would be awkward for e.g. terraform-only stuff.

**Comment by kke** [comment]
`grep k0sctl hack/tool/go.mod|cut -d" " -f2` :)

**Comment by twz123** [comment]
You can try to cook up something, if you like :sweat_smile:

**Pull request merged**
