### PR TITLE
Document constraints of dynamic config install

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description

I got a report of someone who had issues becuase the `kubernetes.default.svc` `clusterIP` was missing from the SANs of some control plane nodes. This happened because the certificate for kube-apiserver is generated without dynamic config. [In the past we saw a similar issue with specifying `spec.network.provider`](https://github.com/k0sproject/k0s/issues/3304),  but because it was reported in k0sctl we only fixed it for k0sctl.

We don't document anywhere this behavior but we copy it in  k0sctl and in k0smotron we use the same configuration for every replica of the statefulset, we should tell .

Non-changeable fields can cause issues if not defined in the configuration file. This isn't immediately obvious by reading the docs so document it explicitly.

This was in the past 

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue) (I consider this a documentation bug)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
Tagged it to backport to 1.30 only because the older versions need a manual backport due to CPLB.

**Review by twz123 — APPROVED** [review]
I wonder if there's anything stopping us from actually supporting this to be dynamically reconciled? It currently _feels_ like all that is needed is to add a `Reconcile` method to the `Keepalived` struct.

**Comment by juanluisvaladas** [comment]
> I wonder if there's anything stopping us from actually supporting this to be dynamically reconciled? It currently feels like all that is needed is to add a Reconcile method to the Keepalived struct.

I discussed this with Jussi back in the day and we agreed we didn't want to support this because:
1- kube-apiserver relies con CPLB, if something goes wrong this creates a chicken-egg situation.
2- Some fields such as the interface might be different on a per node basis, for instance the interface used for VRRP instances.

**Comment by twz123** [comment]
> 1- kube-apiserver relies con CPLB, if something goes wrong this creates a chicken-egg situation.

I don't see why kube-apiserver is relying on that? If yes, then because users have actively configured it in that way.

> 2- Some fields such as the interface might be different on a per node basis, for instance the interface used for VRRP instances.

Right. Currently, k0s is only able to reconcile cluster-wide settings. Maybe that's something to be revisited in the future.

**Comment by juanluisvaladas** [comment]
> I don't see why kube-apiserver is relying on that? If yes, then because users have actively configured it in that way.

This is used to fill the SANs of the kube-apiserver certificate. I think that was the only thing where it affected apiserver.

**Pull request merged**
