### PR TITLE
Copyright 2023

### PR DESCRIPTION
**Pull request by twz123**
## Description

Update all copyright comments from 2022 to 2023.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
A single digit in copyright means the first year and not the last year. Not quite sure about the legal implications of this, but I don't think this is correct. For instance kubernetes displays the year where the file was created:
https://github.com/kubernetes/kubernetes/blob/83afc363a62782ccafab77199df4195581f55dc4/hack/update-vendor-licenses.sh#L2
https://github.com/kubernetes/kubernetes/blob/83afc363a62782ccafab77199df4195581f55dc4/hack/update-generated-api-compatibility-data.sh#L3
https://github.com/kubernetes/kubernetes/blob/83afc363a62782ccafab77199df4195581f55dc4/hack/update-conformance-yaml.sh#L3

**Comment by twz123** [comment]
I was basically following the tradition:


- 55302b07c Mass-replace copyright boilerplate year (#1413)
- 19f771028 Add filename usage hint to "k0s restore" (#1414)
- 4faed99bf Update copyright boilerplate year and add CI check (#1407)
- 22d79cc25 Merge pull request #724 from jnummelin/update-copyrights
- abb34dcd5 Update copyright to 'Copyright 2021 k0s authors'
- 5a34b4952 Add copyright and license boilerplate (#319)

**Comment by juanluisvaladas** [comment]
I'll ask Mirantis' legal team.

**Comment by twz123** [comment]
Closing in favor of #2718

**Pull request closed without merging**
