### PR TITLE
Avoid erroring out when localhost cannot be resolved

### PR DESCRIPTION
**Pull request by twz123**
## Description

During certificate generation, k0s makes an effort to compile a comprehensive list of SANs for the TLS certificates. Consequently, it tries to ensure that connections from localhost will function properly: It attempts to perform a lookup for localhost to include its IP address in the list of SANs. Although this lookup is typically expected to succeed, as it's assumed to be local to the machine anyways, it may fail in specific setups, leading to cluster formation issues.

Instead of treating a failed IP lookup for localhost as a critical error, record the error in the logs and proceed with the execution. This approach is likely to be effective if localhost resolves to its standard address, 127.0.0.1.

Additionally, introduce some log statements to capture errors that would otherwise go unnoticed, such as those arising from attempts to resolve the machine's hostname.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by kke — APPROVED** [review]

**Comment by twz123** [comment]
As said in https://github.com/k0sproject/k0s/issues/3351#issuecomment-1673538675: I'm not sure if this patch helps much. Maybe it will make things worse, because I'm pretty sure that k0s will just not work when localhost cannot be resolved, and subsequent errors might be more obscure and less obvious. Should we merge it nonetheless?

Maybe we should have some sysinfo probe with a name lookup for localhost, at least.

**Comment by ncopa** [comment]
I'm thinking that if `localhost` does not resolve, something is seriously broken and its better to fail early.

**Comment by twz123** [comment]
Agree. Other parts of the code really rely on localhost being resolvable.

**Pull request closed without merging**
