### PR TITLE
docs: add file-structure

### LINKED ISSUE #951: Document k0s directories
Documentation should include a list of directories and their purposes, what goes in there and expected permissions etc.

- data-dir (/var/lib/k0s)
- run-dir (/var/run/k0s)
- bin-dir (/var/lib/k0s/bin?)

### PR DESCRIPTION
**Pull request by wenerme**
## Description

Fixes #951

describe the directory and file used by k0s

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by jnummelin** [comment]
@wenerme linter is not happy, check the `Files Changed` tab for its complaints.

**Comment by kke** [comment]
Thinking if it would be feasible to change all file/path references in k0s code to some kind of `NamedPath` objects that could be used to generate docs (or code would be generated from the doc) 🤔

**Comment by wenerme** [comment]
@kke windows support is experimental, may change later, and even use windows, there must have a controller+worker run in linux

**Comment by kke** [comment]
> windows support is experimental, may change later, and even use windows, there must have a controller+worker run in linux

Yes, but we do have several `FooFooDefaultWindows` paths in the constants. This could be something like `namedpath.Get("rundir").Default()` and it would return the correct one depending on `GOOS`.

> A mapping of path to explain is good idea, but not easy to maintain

Could be easier than maintaining separately in docs.

**Comment by wenerme** [comment]
I haven't deploy k0s on windows before, I can update the doc after I have some experience about windows k0s deployment.

**Comment by trawler** [comment]
I am not convinced that a full listing of all files used by k0s, add meaningful information to the docs. 
Many of the listed files are auto-generated, and manipulating them will likely break k0s functionality if modified directly.
A concise description of the directory structure, directory contents and its uses and important configuration file paths would be more useful, in my opinion.

**Comment by soider** [comment]
>I am not convinced that a full listing of all files used by k0s, add meaningful information to the docs.

I'd love to agree. The thing with listing all the files in the docs is that:
- it is now a contract to maintain that port of the documentation
- a lot of those files are actually used internally

**Comment by trawler** [comment]
@wenerme: I think that such a detailed file and directory list defeats the purpose, and doesn't add as much value as expected. 
It includes files and directories that are auto-generated and may confuse users into trying to touch/edit the files, and this PR doesn't contain an explanation on the source and purpose of these files.
I would instead love to see the info in this PR added to https://docs.k0sproject.io/latest/architecture/
as a new segment: File Structure, with the general information of each directory, its' uses and the main configuration files (user configuration files, not system configuration files).
For example, list /var/lib/k0s: the main data directory for k0s and all it’s components, customizable with --data-dir flag and /var/lib/k0s/pki: CAs, keys and certificates managed by k0s for all kubernetes components, etc.
For other files: if it's necessary to list files like kubelet.conf / kubelet-config.yaml / kubelet-bootstrap.conf, etc, it's worth mentioning that these files should not be edited by hand, but instead are generated by k0s.

**Review by trawler — CHANGES_REQUESTED** [review]
@wenerme: I think that such a detailed file and directory list defeats the purpose, and doesn't add as much value as expected.
It includes files and directories that are auto-generated and may confuse users into trying to touch/edit the files, and this PR doesn't contain an explanation on the source and purpose of these files.
I would instead love to see the info in this PR added to https://docs.k0sproject.io/latest/architecture/
as a new segment: File Structure, with the general information of each directory, its' uses and the main configuration files (user configuration files, not system configuration files).
For example, list /var/lib/k0s: the main data directory for k0s and all it’s components, customizable with --data-dir flag and /var/lib/k0s/pki: CAs, keys and certificates managed by k0s for all kubernetes components, etc.
For other files: if it's necessary to list files like kubelet.conf / kubelet-config.yaml / kubelet-bootstrap.conf, etc, it's worth mentioning that these files should not be edited by hand, but instead are generated by k0s.

**Comment by wenerme** [comment]
@trawler Ok, I will split the content, only keep the k0s related file.

**Comment by till** [comment]
Would be great to have a list of directories that I **can** adjust.

**Pull request closed without merging**
