### PR TITLE
Extra arguments from K0S_EXTRA_ARGS in service startup

### PR DESCRIPTION
**Pull request by kke**
## Description

This was talked about at some point. This will make the service script installed by `k0s install` read extra arguments from `K0S_EXTRA_ARGS`.

This can be defined in:
- `/etc/conf.d/k0s{{role}}]` in openrc
- `/etc/default/k0s{{role}}` in sysv
- `/etc/sysconfig/k0s{{role}}.conf` in upstart
- `/etc/systemd/system/k0s{{role}}.env` in systemd

Darwin launchd is not modified as it would require some kind of a wrapper and k0s doesn't work there to begin with.

The systemd template was moved into its own file from service.go like all the others are.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [ ] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by twz123 — APPROVED** [review]
Just a quick reminder, wouldn't be `k0s install --force` a viable alternative to this?

**Comment by kke** [comment]
> Just a quick reminder, wouldn't be `k0s install --force` a viable alternative to this?

Yes but less conventional.

**Comment by twz123** [comment]
Shall we merge this @kke?

**Comment by kke** [comment]
I don't know. It's perhaps a bit more conventional but also it's one more place to fiddle with configuration.

**Pull request closed without merging**
