### PR TITLE
Bump kubernetes to 1.20.1

### PR DESCRIPTION
**Pull request by ncopa**
Signed-off-by: Natanael Copa <ncopa@mirantis.com>

---
name: Pull Request
about: Create a Pull Request
title: ''
labels: ''
assignees: ''

---

**Issue**
Fixes #{ issue number }

**What this PR Includes**
A short description of what this PR does.

### CODE REVIEW

**Comment by ncopa** [comment]
This should probably be merged after #569

**Comment by ncopa** [comment]
Passes check-network: https://github.com/k0sproject/k0s/actions/runs/437571209

**Review by jnummelin — APPROVED** [review]

**Review by trawler — CHANGES_REQUESTED** [review]
we should also update `pkg/component/server/kubeletconfig_test.go`

**Comment by trawler** [comment]
> we should also update `pkg/component/server/kubeletconfig_test.go`

ah no, my mistake. profile name doesn't include minor version. lgtm!

**Review by trawler — APPROVED** [review]

**Pull request merged**
