### PR TITLE
bug: add support for image tag and digest

### PR DESCRIPTION
**Pull request by emosbaugh**
## Description

When adding an envoy image with tag and digest I get a failure:

>  invalid node config: spec: network: nodeLocalLoadBalancing.envoyProxy.image.version: Invalid value: "1.29.5-r0@sha256:7856e4d51f6631b1121c79ec93958897f1d90a52ce8d1d3513cff73df6821a2b": must match regular expression: ^[\w][\w.-]{0,127}$

This change adds support for an optional digested image reference.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by twz123** [comment]
Darn! That was definitely an oversight. Surprising that there's no ready-made constant for this in `github.com/distribution/reference`. I wonder if it makes sense to simply use a single string instead of the image/version struct in a potential config version v2. This is how it's done in upstream Kubernetes anyways. Then we could use [`github.com/distribution/reference.ReferenceRegexp`](https://pkg.go.dev/github.com/distribution/reference@v0.6.0#ReferenceRegexp).

Fixes #2428.

**Review by twz123 — APPROVED** [review]
Thanks a lot!

**Comment by sgalsaleh** [comment]
Is it possible to backport this fix to 1.28 as well?

**Comment by twz123** [comment]
> Is it possible to backport this fix to 1.28 as well?

This is going into all supported releases, i.e. down to 1.27.

**Comment by emosbaugh** [comment]
@twz123 I wanted to call out that `ClusterImages.Validate` [does not](https://github.com/k0sproject/k0s/blob/25941d8b934c776ce27f7b31b09e361e885fff38/pkg/apis/k0s/v1beta1/images.go#L100) call `ImageSpec.Validate`. Validate is only called for the envoy image. I unintentionally pushed [this test](https://github.com/k0sproject/k0s/pull/4792/files#diff-df8b5f1d36967d976cd305146646a7119907b0c8104eb4d54862a07e2a130778R85) which would have failed had it been called. Is there any follow up action you would like me to take here like to remove the test? Thanks for the quick turnaround!

**Comment by twz123** [comment]
>I wanted to call out that `ClusterImages.Validate` [does not](https://github.com/k0sproject/k0s/blob/25941d8b934c776ce27f7b31b09e361e885fff38/pkg/apis/k0s/v1beta1/images.go#L100) call `ImageSpec.Validate`.

That explains why this didn't crop up earlier.

> Is there any follow up action you would like me to take here like to remove the test? 

Actually validating the images in `ClusterImages.Validate` seems reasonable to me. PRs are welcome, as always :upside_down_face:

**Pull request merged**
