### PR TITLE
Fix helm race condition

### LINKED ISSUE #3282: Updates to helm extensions are not applied
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Version

1.27.3+k0s.0

### Sysinfo

_No response_

### What happened?

I installed k0s using k0sctl, providing the k0s configuration inside of `k0sctl.yaml`. Here I specified that I want to install Traefik as a Helm extension, which worked correctly - once the cluster was bootstrapped, there was a Traefik instance up and running.

Then I went ahead and customized `values` inside of `k0sctl.yaml`, adjusting things like the replica count and adding `hostPort`s.
After applying my changes using `k0sctl apply`, I found that there is still just a single replica of Traefik running.

Browsing through existing issues I found #3071 - which made me aware of the `charts.helm.k0sproject.io` CRD, which I found inside `kube-system`. Unfortunately I don't have the exact console output anymore, but I could gather from a `kubectl describe` on this CRD that it received the new configuration in its `spec`, however in `status` it said something along the lines of `cannot re-use a name that is still in use`, making me think it tried to perform a fresh install for Traefik instead of an upgrade.

### Steps to reproduce

1. install cluster using `k0sctl apply` with Traefik as Helm extension, `.spec.extensions.helm`:
```
            repositories:
            - name: traefik
              url: https://traefik.github.io/charts
            charts:
            - name: traefik
              chartname: traefik/traefik
              version: "23.1.0"
              namespace: traefik
```

2. after cluster is bootstrapped, modify `values` for Helm extension in k0s config:
```
              values: |
                deployment:
                  replicas: 3
                ports:
                  traefik:
                    hostPort: 9000
                  web:
                    hostPort: 8000
                  metrics:
                    hostPort: 9100
```
3. run `k0sctl apply` again

### Expected behavior

The Helm installation of Traefik is upgraded with the new values.

### Actual behavior

The original Traefik configuration was retained.

### Screenshots and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description

The PR includes three commits.

The first commit removes the field concurrencyLevel in helm controller. This field isn't honored at all and we want to remove concurrent reconciliation anyway so entirely remove the field.

The second commit makes extensions controller thread-safe. Helm is unable to reconcile multiple charts at the same time because /var/lib/k0s/helmhome/cache/ is shared between charts and helm cache was not designed to be safe to be used concurrently. To fix it we document some functions of the Commands struct are not thread safe (they couldn't have a local lock unless it was shared across all instances) and modify the controller not concurrent.

The third commit implements timeouts, we were already passing a context but this wasn't used at all. This is to prevent a reconciler being stuck forever 

Requirement to fix #3282 and #3433

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by twz123** [comment]
Could you add a bit of explanation of the problem and its fix in the PR description (and possibly the commit message)?

**Comment by juanluisvaladas** [comment]
> Could you add a bit of explanation of the problem and its fix in the PR description (and possibly the commit message)?

Oh sorry, added a proper explanation.

**Review by twz123 — DISMISSED** [review]

**Comment by juanluisvaladas** [comment]
After speaking with Tom we agreed this isn't really thread safe. It's less racy as I couldn't reproduce the helm condition myself but it needs further work. Can't merge it yet

**Review by twz123 — APPROVED** [review]
:tada:

**Review by twz123 — APPROVED** [review]

**Comment by jannispl** [comment]
I pointed out in #3282 that there is a lack of documentation regarding the invocation with `--wait` for Helm chart installations, is this something that should be addressed here, as my original issue was closed with reference to this one?

**Comment by juanluisvaladas** [comment]
Hi @jannispl your issue should have never been closed. I think the bot closed it because of the sentence: "Requirement to fix https://github.com/k0sproject/k0s/issues/3282 and https://github.com/k0sproject/k0s/issues/3433"  but that was never intended. Part of those issues are solved now but we're not done just yet.

**Comment by twz123** [comment]
/xref #2974, which introduced the concurrencyLevel which has been removed here

**Pull request merged**
