### PR TITLE
Allow setting environment with the install command

### LINKED ISSUE #1054: Allow setting environment in "k0s install"
Related to #1037 and https://github.com/k0sproject/k0sctl/pull/184 

It would be nice if you could pass environment variables to be set in the script installed by `k0s install`, something like `k0s install controller -e ETCD_UNSUPPORTED_ARCH=arm64`

### PR DESCRIPTION
**Pull request by makhov**
## Description

Fixes #1054

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by kke — COMMENTED** [review]
Does this only work on systemd?

**Comment by makhov** [comment]
Yes, at the moment. Do we have a list of supported init systems btw? Which of them should I check? And do I need to support Windows here?

**Comment by kke** [comment]
https://github.com/kardianos/service README says "Windows, Linux/(systemd | Upstart | SysV) and OSX/Launchd." but seems it supports OpenRC as well (according to merged commits).

**Review by kke — APPROVED** [review]
Nice, could be sent upstream to kardianos/service.

**Pull request merged**
