### PR TITLE
Use go 1.21.0

### PR DESCRIPTION
**Pull request by kke**
## Description

[Announcement](https://groups.google.com/g/golang-announce/c/Mk0Jar6hfhI)

[Release Notes](https://go.dev/doc/go1.21)

[Blog](https://go.dev/blog/go1.21)

### CODE REVIEW

**Review by makhov — APPROVED** [review]

**Review by ncopa — APPROVED** [review]

**Comment by twz123** [comment]
I wonder if we need to fix the release workflow for ARMv7, since Go changed its "dot zero" versioning scheme. Something similar has been done in #3193 for the PR workflows, but the release workflow has been overlooked in that PR:

https://github.com/k0sproject/k0s/blob/f3db9b6eb4daf6f5c22a7d6b2a37e0ec85050abc/.github/workflows/release.yml#L285

**Comment by kke** [comment]
It would be nice if there was a download link for "latest 1.21.x". 

With 1.20 the current implementation will download 1.20.0 if you give "1.20" or "1.20.0". (1.20.tar.gz contains v1.20, not the latest v1.20.7).

**Comment by kke** [comment]
> Go 1.21 now defines that if a goroutine is panicking and recover was called directly by a deferred function, the return value of recover is guaranteed not to be nil. To ensure this, calling panic with a nil interface value (or an untyped nil) causes a run-time panic of type [*runtime.PanicNilError](https://tip.golang.org/pkg/runtime/#PanicNilError).

>To support programs written for older versions of Go, nil panics can be re-enabled by setting GODEBUG=panicnil=1. This setting is enabled automatically when compiling a program whose main package is in a module that declares go 1.20 or earlier.

I think we can just keep 1.19 in go.mod for k8s <= 1.26 and 1.20 for current and build all of them using go 1.21.

**Comment by ncopa** [comment]
upstream kubernetes 1.28.0 is built with go1.20.7:
```
$ go version kubernetes/client/bin/kubectl
kubernetes/client/bin/kubectl: go1.20.7
```

**Comment by kke** [comment]
I think https://github.com/kubernetes/release/issues/3076 is the issue to track

**Comment by kke** [comment]
Already at 1.21.6

**Pull request closed without merging**
