### PR TITLE
Add metricsBindAddress parameter to kubeProxy conf

### LINKED ISSUE #1544: I want to change MetricsBindAddress of kube-proxy, but the parameter does not exist in k0s.yaml.
### Is your feature request related to a problem? Please describe.

Looking at /var/lib/k0s/manifests/kubeproxy/kube-proxy.yaml, metricsBindAddress is set to "" on ConfigMap.
Even if I edit the manifest file directly, it reverts to default when I restart k0s.
So please make it possible to edit that parameter in k0s.yaml.

### Describe the solution you would like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description
Prior to this the value was hardcorded.
Fixes #1544

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
I populated the corresponding files manually, this seems to have bee done with kubebuilder, however make manifests doesn't seem to work and I haven't found the appropriate way to do this so most likely I'm missing some step here. I would appreciate some corrections.

**Review by jnummelin — APPROVED** [review]
LGTM

**Comment by twz123** [comment]
> I populated the corresponding files manually, this seems to have bee done with kubebuilder, however make manifests doesn't seem to work and I haven't found the appropriate way to do this so most likely I'm missing some step here. I would appreciate some corrections.

A simple `make` should have run `controller-gen` to regenerate the manifests. Didn't that work?

**Comment by juanluisvaladas** [comment]
> > I populated the corresponding files manually, this seems to have bee done with kubebuilder, however make manifests doesn't seem to work and I haven't found the appropriate way to do this so most likely I'm missing some step here. I would appreciate some corrections.
> 
> A simple `make` should have run `controller-gen` to regenerate the manifests. Didn't that work?

Yes that worked and it's fine actually, I discussed this on slack with Jussi. Anyway, the thing is that the make manifests target is from kubebuilder and I assumed it just would work but as Jussi found out it's not doing anything at all and it's also broken (throws an error because it depends on a non existing target) so I'm removing them https://github.com/k0sproject/k0s/pull/2393

**Pull request merged**
