### PR TITLE
Use k8s.io/base-component/cli for k0s kubectl command

### PR DESCRIPTION
**Pull request by soider**
Signed-off-by: Mikhail Sakhnov <msakhnov@mirantis.com>
addresses #1405

### CODE REVIEW

**Comment by soider** [comment]
```
sudo ./k0s kc -v=8 get nodes
I0103 11:15:23.599733  509746 loader.go:372] Config loaded from file:  /var/lib/k0s/pki/admin.conf
I0103 11:15:23.601613  509746 round_trippers.go:463] GET https://localhost:6443/apis/metrics.k8s.io/v1beta1?timeout=32s
I0103 11:15:23.601629  509746 round_trippers.go:469] Request Headers:
I0103 11:15:23.601646  509746 round_trippers.go:473]     User-Agent: kc/v0.0.0 (linux/amd64) kubernetes/$Format
I0103 11:15:23.601657  509746 round_trippers.go:473]     Accept: application/json, */*
I0103 11:15:23.608924  509746 round_trippers.go:574] Response Status: 503 Service Unavailable in 7 milliseconds
I0103 11:15:23.608967  509746 round_trippers.go:577] Response Headers:
I0103 11:15:23.608979  509746 round_trippers.go:580]     Audit-Id: 73a33f40-15cc-4092-a878-2fec3941c569
I0103 11:15:23.608988  509746 round_trippers.go:580]     Cache-Control: no-cache, private
I0103 11:15:23.608998  509746 round_trippers.go:580]     Content-Type: text/plain; charset=utf-8
I0103 11:15:23.609007  509746 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0103 11:15:23.609035  509746 round_trippers.go:580]     Content-Length: 20
I0103 11:15:23.609042  509746 round_trippers.go:580]     Date: Mon, 03 Jan 2022 11:15:23 GMT
I0103 11:15:23.611216  509746 request.go:1181] Response Body: service unavailable
I0103 11:15:23.613092  509746 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0103 11:15:23.613141  509746 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0103 11:15:23.613622  509746 round_trippers.go:463] GET https://localhost:6443/apis/metrics.k8s.io/v1beta1?timeout=32s
I0103 11:15:23.613730  509746 round_trippers.go:469] Request Headers:
I0103 11:15:23.613748  509746 round_trippers.go:473]     Accept: application/json, */*
I0103 11:15:23.613796  509746 round_trippers.go:473]     User-Agent: kc/v0.0.0 (linux/amd64) kubernetes/$Format
I0103 11:15:23.614467  509746 round_trippers.go:574] Response Status: 503 Service Unavailable in 0 milliseconds
I0103 11:15:23.614488  509746 round_trippers.go:577] Response Headers:
I0103 11:15:23.614503  509746 round_trippers.go:580]     Audit-Id: cfcf74e1-d01b-43bb-8372-96f42314591a
I0103 11:15:23.614514  509746 round_trippers.go:580]     Cache-Control: no-cache, private
I0103 11:15:23.614523  509746 round_trippers.go:580]     Content-Type: text/plain; charset=utf-8
I0103 11:15:23.614536  509746 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0103 11:15:23.614548  509746 round_trippers.go:580]     Content-Length: 20
I0103 11:15:23.614556  509746 round_trippers.go:580]     Date: Mon, 03 Jan 2022 11:15:23 GMT
I0103 11:15:23.616695  509746 request.go:1181] Response Body: service unavailable
I0103 11:15:23.618833  509746 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0103 11:15:23.618854  509746 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0103 11:15:23.618899  509746 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0103 11:15:23.619362  509746 round_trippers.go:463] GET https://localhost:6443/apis/metrics.k8s.io/v1beta1?timeout=32s
I0103 11:15:23.619391  509746 round_trippers.go:469] Request Headers:
I0103 11:15:23.619408  509746 round_trippers.go:473]     Accept: application/json, */*
I0103 11:15:23.619421  509746 round_trippers.go:473]     User-Agent: kc/v0.0.0 (linux/amd64) kubernetes/$Format
I0103 11:15:23.620148  509746 round_trippers.go:574] Response Status: 503 Service Unavailable in 0 milliseconds
I0103 11:15:23.620166  509746 round_trippers.go:577] Response Headers:
I0103 11:15:23.620171  509746 round_trippers.go:580]     Content-Length: 20
I0103 11:15:23.620179  509746 round_trippers.go:580]     Date: Mon, 03 Jan 2022 11:15:23 GMT
I0103 11:15:23.620188  509746 round_trippers.go:580]     Audit-Id: 64d2fce7-16e2-4107-8164-13417bcbdd8a
I0103 11:15:23.620199  509746 round_trippers.go:580]     Cache-Control: no-cache, private
I0103 11:15:23.620206  509746 round_trippers.go:580]     Content-Type: text/plain; charset=utf-8
I0103 11:15:23.620214  509746 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0103 11:15:23.622040  509746 request.go:1181] Response Body: service unavailable
I0103 11:15:23.624298  509746 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0103 11:15:23.624319  509746 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0103 11:15:23.625397  509746 round_trippers.go:463] GET https://localhost:6443/api/v1/nodes?limit=500
I0103 11:15:23.625416  509746 round_trippers.go:469] Request Headers:
I0103 11:15:23.625423  509746 round_trippers.go:473]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
I0103 11:15:23.625436  509746 round_trippers.go:473]     User-Agent: kc/v0.0.0 (linux/amd64) kubernetes/$Format
I0103 11:15:23.627283  509746 round_trippers.go:574] Response Status: 200 OK in 1 milliseconds
I0103 11:15:23.627303  509746 round_trippers.go:577] Response Headers:
I0103 11:15:23.627318  509746 round_trippers.go:580]     Content-Type: application/json
I0103 11:15:23.627335  509746 round_trippers.go:580]     Content-Length: 2790
I0103 11:15:23.627340  509746 round_trippers.go:580]     Date: Mon, 03 Jan 2022 11:15:23 GMT
I0103 11:15:23.627352  509746 round_trippers.go:580]     Audit-Id: 1f378990-3430-4e0e-838b-fb5977fe77fe
I0103 11:15:23.627365  509746 round_trippers.go:580]     Cache-Control: no-cache, private
I0103 11:15:23.627461  509746 request.go:1181] Response Body: {"kind":"Table","apiVersion":"meta.k8s.io/v1","metadata":{"resourceVersion":"487267"},"columnDefinitions":[{"name":"Name","type":"string","format":"name","description":"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names","priority":0},{"name":"Status","type":"string","format":"","description":"The status of the node","priority":0},{"name":"Roles","type":"string","format":"","description":"The roles of the node","priority":0},{"name":"Age","type":"string","format":"","description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 fo [truncated 1766 chars]
```

**Review by kke — DISMISSED** [review]
LGTM and didn't find any issues in manual tests

**Comment by kke** [comment]
In conflict now, @soider

**Comment by soider** [comment]
@kke I will resolve, but I actually had no time tp debug why the build fails on arm :(

**Comment by ncopa** [comment]
This is also needed for arm64 to pass:

```diff
diff --git a/inttest/kubectl/kubectl_test.go b/inttest/kubectl/kubectl_test.go
index babe49ba..7f97bae9 100644
--- a/inttest/kubectl/kubectl_test.go
+++ b/inttest/kubectl/kubectl_test.go
@@ -59,7 +59,7 @@ func (s *KubectlSuite) TestEmbeddedKubectl() {
                        Check: func(output string, e error) {
                                s.Require().NoError(e)
                                // Check for debug log messages
-                               s.Require().True(strings.HasPrefix(output, "I0104"))
+                               s.Require().True(strings.HasPrefix(output, "I0104") || strings.HasPrefix(output, "I0114"))
                        },
                },
                {
@@ -68,7 +68,7 @@ func (s *KubectlSuite) TestEmbeddedKubectl() {
                        Check: func(output string, e error) {
                                s.Require().NoError(e)
                                // Check for debug log messages
-                               s.Require().True(strings.HasPrefix(output, "I0104"))
+                               s.Require().True(strings.HasPrefix(output, "I0104") || strings.HasPrefix(output, "I0114"))
                        },
                },
                {
@@ -102,7 +102,7 @@ func (s *KubectlSuite) TestEmbeddedKubectl() {
                        Check: func(output string, e error) {
                                s.Require().NoError(e)
                                // Check for debug log messages
-                               s.Require().True(strings.HasPrefix(output, "I0104"))
+                               s.Require().True(strings.HasPrefix(output, "I0104") || strings.HasPrefix(output, "I0114"))
                        },
                },
                {
```

**Comment by soider** [comment]
closed in favor of #1444 which provides other type of fix, without using cli.Run.

**Pull request closed without merging**
