### PR TITLE
Missing backtick in multi-node docs

### PR DESCRIPTION
**Pull request by matti**
## Description

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [ ] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by kke — APPROVED** [review]

**Comment by jnummelin** [comment]
@matti DCO not happy, need to get signed commits... 😄

**Comment by matti** [comment]
:________D

**Comment by ncopa** [comment]
> @jnummelin wat do - wheres DCO instructions

https://github.com/k0sproject/k0s/pull/1511/checks?check_run_id=5167888598

**Comment by matti** [comment]
I initially made this commit with githubs "edit" feature - clicking edit and hitting "save".  This DCO stuff is why we can't have nice things.I think you can keep the backtick as is and I don't contribute edits anymore.

**Pull request closed without merging**
