### PR TITLE
remove --enable-hostpath-provisioner flag from kube-controller-manager

### PR DESCRIPTION
**Pull request by carlory**
## Description

See https://github.com/kubernetes/kubernetes/issues/123804

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [ ] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by carlory** [comment]
hi @makhov @jnummelin how do I re-run failing tests?

**Comment by carlory** [comment]
The `Go build / Smoke test on armv7/arm64 (arm) (pull_request) `  job fails again, can you re-trigger it? @twz123 Thank you.

```
Attempt 1 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 3000 ms...
Attempt 2 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 5205 ms...
Attempt 3 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 9079 ms...
Attempt 4 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 14[19](https://github.com/k0sproject/k0s/actions/runs/8277275161/job/22654995825?pr=4165#step:13:20)5 ms...
Error: Failed to CreateArtifact: Failed to make request after 5 attempts: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact
```

**Comment by carlory** [comment]
1 skipped and 72 successful checks

kindly ping @twz123 please take a look again, thanks

**Review by twz123 — APPROVED** [review]
Thanks @carlory for patching downstream projects, and sorry for the delay! :+1:

**Pull request merged**
