### PR TITLE
Remove build example from docs/experimental-windows.md

### LINKED ISSUE #1032: Update documentation for windows nodes
The [documentation](https://docs.k0sproject.io/v1.21.2+k0s.1/experimental-windows/) for windows claims that you should start with building the windows binary with `make clean k0s.exe`. I believe that needs to be updated because:

- users think this should be done from a windows machine, while we cross compile k0s.exe from linux
- the `make clean` should no longer be needed since 31d3e8b7bd86b6a0fdbbd8e0626836524b30679a
- we provide pre-compiled windows binaries nowdays, so we can probably drop the build part from user documentation

### PR DESCRIPTION
**Pull request by qiuge615**
Signed-off-by: qiuge615 <speedingq@gmail.com>

---
name: Pull Request
about: Create a Pull Request
title: 'Remove build example from docs/experimental-windows.md'
labels: 'doc'
assignees: 'qiuge615'

---

**Issue**
Fixes #1032 

**What this PR Includes**
Remove Windows build part from user documentation. Update typos in the same document.

### CODE REVIEW

**Comment by qiuge615** [comment]
@kke Thank you for your suggestions in my previous PR, but I am sorry that I could add signoff in that PR since I am not using my personal email and I can not accept the DCO. So I create a new PR with the same changes, please review, thanks.

**Review by soider — APPROVED** [review]

**Comment by soider** [comment]
@qiuge615 there are some linting warning about the markdown in the documentation, can I ask you to address them?

**Review by kke — CHANGES_REQUESTED** [review]
Need to fix the markdown lint error (two consecutive empty lines starting from row 15)

**Comment by qiuge615** [comment]
@soider @kke Thank you for your suggestions. I removed the extra empty line, please review.

**Review by kke — APPROVED** [review]

**Pull request merged**
