### PR TITLE
Replace image validity check with shell script

### PR DESCRIPTION
**Pull request by twz123**
## Description

The script is more or less straight forward and saves us some go dependencies and a custom go build execution.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by twz123** [comment]
On the other hand, is this functionality still useful? K0s ships its own images anyways, so it's under the project's control to provide appropriate multi-arch images anyways.

**Comment by jnummelin** [comment]
> We could simply remove it?

I wonder would we catch any missing archs in smokes? For most of the images probably yes, but we're not really running with all permutation configs for arm/arm64 smokes that would exercise all the images.

**Comment by twz123** [comment]
My point here is that the default images are all built by the k0s project. How likely is it that we're forgetting to ship an architecture? I guess this was a bigger concern back in the day when k0s used upstream images verbatim.

**Comment by twz123** [comment]
Plus, wouldn't the airgap image tarball generation fail when an image is unavailable for a certain architecture?

**Comment by jnummelin** [comment]
> How likely is it that we're forgetting to ship an architecture? 

Quite low I'd say

> wouldn't the airgap image tarball generation fail when an image is unavailable for a certain architecture?

I think you're right, it would AFAIK fail.

So maybe we should just remove this stuff

**Comment by twz123** [comment]
Superseeded by #3913.

**Pull request closed without merging**
