### PR TITLE
Add an example for deploying K0s to a Raspberry Pi 4 cluster

### PR DESCRIPTION
**Pull request by shaneutt**
**What this PR Includes**

This adds a new example in `/examples` that users can use or study to deploy K0s onto a cluster running ARM64, with a particular emphasis on using Raspberry Pi 4 systems.

### CODE REVIEW

**Comment by jnummelin** [comment]
@shaneutt Thanks for the PR.

Just wondering if it would be possible / makes sense to re-use what has already been done for general Ansible at: https://github.com/movd/k0s-ansible

We already have a example also for it at: https://github.com/k0sproject/k0s/blob/main/docs/examples/ansible-playbook.md

**Comment by shaneutt** [comment]
> @shaneutt Thanks for the PR.
> 
> Just wondering if it would be possible / makes sense to re-use what has already been done for general Ansible at: https://github.com/movd/k0s-ansible
> 
> We already have a example also for it at: https://github.com/k0sproject/k0s/blob/main/docs/examples/ansible-playbook.md

Hi @jnummelin thank you for your considerations :bow: 

The intention here was to focus on Raspberry Pis, and the use of Ansible was meant to be convenient, but teaching ansible wasn't the specific point, so I wonder: if I were to remove Ansible from the equation or otherwise change this example do you think there's some way we could make it align better with your expectations for examples in this repo?

Or perhaps more generally: could you please help me to better understand what you're looking for in examples submitted to this repository?

**Comment by jnummelin** [comment]
I think we want to have examples that cover wide range of use cases and deployment architectures to guide the community.

The example itself is good and fit's perfectly the above goal, I'm just mainly thinking out loud if we could re-use the ansible bits so we do not end up having two examples with totally different ansible playbooks.

**Comment by shaneutt** [comment]
To avoid having multiple split ansible playbooks like you're suggesting, I'm considering removing the ansible parts here and focusing instead on showing the commands needed for this specific kind of environment, making this lean a little bit more to being a documentation example over being more of a functional example.

My proposal for action items is:

1. remove the ansible
2. move the commands and context into the README.md
3. submit it again as a PR against `examples/`

What are your thoughts on that? Do you prefer a different approach?

**Comment by jnummelin** [comment]
Sounds like a good plan 👍

**Comment by shaneutt** [comment]
@jnummelin updated it according to our previous discussion, let me know what you think.

**Review by jnummelin — APPROVED** [review]
Good stuff. Thanks @shaneutt

**Pull request merged**
