### PR TITLE
Update cloud-providers.md

### PR DESCRIPTION
**Pull request by KennethEhmsen**
Change fro to from

---
name: Pull Request
about: Create a Pull Request
title: ''
labels: ''
assignees: ''

---

**Issue**
Fixes #{ issue number }

**What this PR Includes**
A short description of what this PR does.

### CODE REVIEW

**Comment by jasmingacic** [comment]
@KennethEhmsen can you please signoff your commit so we can merge this.

**Comment by ncopa** [comment]
Please see https://github.com/k0sproject/k0s/pull/410/checks?check_run_id=1410726544 how to sign off the commit. Thanks!

**Comment by KennethEhmsen** [comment]
I am trying to SignOff on the Patch-1, unfortunately it fails for some reason, but hang on I will investigate the issue.

**Comment by KennethEhmsen** [comment]
I Will close this one and check it out again, and then commit the new one

**Pull request closed without merging**
