### PR TITLE
[Backport release-1.25] Fix dualstack config propagation in dynamic config mode

### PR DESCRIPTION
**Pull request by twz123**
Backport of #2251. See #2220.

### CODE REVIEW

**Comment by twz123** [comment]
This PR triggered the [same CI error](https://github.com/k0sproject/k0s/actions/runs/3523149538/jobs/5940084044) as its original, hence backporting the appropriate fix first: #2447.

**Review by soider — APPROVED** [review]
Approved but disabled auto merge since I ain't sure if everything is ready to merge it

**Comment by makhov** [comment]
@twz123 is it safe to merge?

**Comment by twz123** [comment]
Ah, yes. It's a backport that was forgotten back in the day. Tests pass, and I've set it to auto merge. From my POV this is good to go.

**Comment by pinghe** [comment]
1.24 branches not merged

**Pull request merged**
