### PR TITLE
Add lint for package import order

### PR DESCRIPTION
**Pull request by twz123**
## Description

Add lint for package import order via gci. Apply the new format to all the go files.

Also lint inttests and fix all the linter errors. Mostly go header formatting, but also a variable naming, function argument ordering and a missing err check.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
I would prefer if the changes in .golangci and the Makefiles were in a separate commit so that we have a cleaner history, but the other than that it looks good to me.

Regarding the order of the imports, I don't really care either.

**Comment by twz123** [comment]
> I would prefer if the changes in .golangci and the Makefiles were in a separate commit so that we have a cleaner history [...]

They are, or am I missing something? The first commit adds the inttests to the Makefile and addresses the lints there, the second adds gci to the golangci-lint config and changes the imports.

**Comment by s0j** [comment]
Won't this be an intentional barrier to entry? Most IDEs will autoformat imports automatically, and if they don't adhere to the linting rules (or have the option to customize), every PR will result in lint failures. Sure the argument would be 'run make lint before PR', but this just feels like a bit of an overreach.

**Comment by juanluisvaladas** [comment]
> > I would prefer if the changes in .golangci and the Makefiles were in a separate commit so that we have a cleaner history [...]
> 
> They are, or am I missing something? The first commit adds the inttests to the Makefile and addresses the lints there, the second adds gci to the golangci-lint config and changes the imports.

what I meant is one commit for the inports in the go code and a second commit the changes in the build system so that the history is a bit cleaner. So that would be a total of 3 or four commits.

**Comment by mikhail-sakhnov** [comment]
As the previous comment with еру suggestion to close the PR as staled got no reaction, I interpret it like there are no objections to close it :)

**Pull request closed without merging**
