### PR TITLE
Propagate error when deleting stack

### PR DESCRIPTION
**Pull request by cPu1**
## Description

The error returned from `getPruneableResources` was not being propagated to the caller. This changelist fixes that by propagating the error. The usage of `sync.WaitGroup` has been replaced with a context-aware `errgroup.Group` to allow failing fast by terminating other go-routines when one of the API server calls fails. The usage of `sync.Mutex` has also been replaced with a buffered channel.

In the future, it might be worth considering bounding the number of go-routines spawned to avoid hitting API rate limits, and to turn the `prune` method into a streaming pipeline that spawns separate go-routines for finding and deleting prunable resources, instead of listing all prunable resources first before starting the deletion. If this is of interest, I am happy to work on this in a separate PR. 

The checks listed [here](https://github.com/k0sproject/k0s/blob/main/docs/contributors/testing.md#run-local-verifications) are passing. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [x] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by twz123** [comment]
Thanks for working on this!

> The error returned from `getPruneableResources` was not being propagated to the caller. This changelist fixes that by propagating the error.

Just out of curiosity, did you notice any swallowed errors, or did you just want to address the FIXME?

> The usage of `sync.WaitGroup` has been replaced with a context-aware `errgroup.Group` to allow failing fast by terminating other go-routines when one of the API server calls fails.

Cool!

> The usage of `sync.Mutex` has also been replaced with a buffered channel.

Not sure about this. I'd keep the mutex due to its simplicity. There's just a little contention when storing the outcome, all the network traffic will happen concurrently. If the lock 
is a real problem, then I'd not use a channel, 


> 
> In the future, it might be worth considering bounding the number of go-routines spawned to avoid hitting API rate limits, and to turn the `prune` method into a streaming pipeline that spawns separate go-routines for finding and deleting prunable resources, instead of listing all prunable resources first before starting the deletion. If this is of interest, I am happy to work on this in a separate PR.
> 
> The checks listed [here](https://github.com/k0sproject/k0s/blob/main/docs/contributors/testing.md#run-local-verifications) are passing.
> ## Type of change
> 
>     * [ ]  Bug fix (non-breaking change which fixes an issue)
> 
>     * [x]  New feature (non-breaking change which adds functionality)
> 
>     * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
>     * [ ]  Documentation update
> 
> 
> ## How Has This Been Tested?
> 
>     * [ ]  Manual test
> 
>     * [x]  Auto test added
> 
> 
> ## Checklist:
> 
>     * [x]  My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project
> 
>     * [x]  My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
> 
>     * [x]  I have performed a self-review of my own code
> 
>     * [x]  I have commented my code, particularly in hard-to-understand areas
> 
>     * [ ]  I have made corresponding changes to the documentation
> 
>     * [x]  My changes generate no new warnings
> 
>     * [ ]  I have added tests that prove my fix is effective or that my feature works
> 
>     * [x]  New and existing unit tests pass locally with my changes
> 
>     * [ ]  Any dependent changes have been merged and published in downstream modules
> 
>     * [x]  I have checked my code and corrected any misspellings

**Comment by twz123** [comment]
Oops. Wanted to write a comment and hit a wrong shortcut apparently :see_no_evil:

**Comment by twz123** [comment]
Thanks for working on this!

> The error returned from `getPruneableResources` was not being propagated to the caller. This changelist fixes that by propagating the error.

Just out of curiosity, did you notice any swallowed errors, or did you just want to address the FIXME?

> The usage of `sync.WaitGroup` has been replaced with a context-aware `errgroup.Group` to allow failing fast by terminating other go-routines when one of the API server calls fails.

Cool!

> The usage of `sync.Mutex` has also been replaced with a buffered channel.

Not sure about this. I'd keep the mutex due to its simplicity. There's just a little contention when storing the outcome, all the network traffic will happen concurrently.

> In the future, it might be worth considering bounding the number of go-routines spawned to avoid hitting API rate limits, and to turn the `prune` method into a streaming pipeline that spawns separate go-routines for finding and deleting prunable resources, instead of listing all prunable resources first before starting the deletion. If this is of interest, I am happy to work on this in a separate PR.

I have long wondered how this part of k0s could be improved. The stack applier is sort of an ultra-minimalistic Flux/Argo CD implementation. There's probably something™ out there that we could use instead of reinventing the wheel here. So I'd rather see if k0s could incorporate Argo CD's [GitOps Engine](https://github.com/argoproj/gitops-engine) or a comparable library before putting a lot of work into improving the existing code. If that turns out to be a dead end, then I'd start improving the existing stuff.

**Comment by jnummelin** [comment]
> I have long wondered how this part of k0s could be improved. The stack applier is sort of an ultra-minimalistic Flux/Argo CD implementation. There's probably something™ out there that we could use instead of reinventing the wheel here. So I'd rather see if k0s could incorporate Argo CD's [GitOps Engine](https://github.com/argoproj/gitops-engine) or a comparable library before putting a lot of work into improving the existing code. If that turns out to be a dead end, then I'd start improving the existing stuff.

I fully agree with this. I'd also rather see k0s adapting something existing from the GitOps ecosystem, if possible. @cPu1 as you've working on that side of things, maybe you might have some better idea if there is something we could adapt?

**Pull request closed without merging**
