### PR TITLE
Make prometheus.io/scrape annotation configurable

### LINKED ISSUE #3165: Prometheus is enabled using annotations by default on most components
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Not important (rh8)
```

### Version

1.2.26 - but master has it too

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

prometheus annotations enable scraping for kube-system components (https://github.com/k0sproject/k0s/blob/73a8a11d56c8e0c7535f45c22f9739440c12635e/pkg/component/controller/kubeproxy.go#L312), would be great to make it togglable and deactivable for instances where prometheus is not intended for core components, in particular when it does not work out of the box cause the node ip is not accessible to prometheus for ex.

### Steps to reproduce

Start k0s (in single node mode for ex) .

### Expected behavior

Check annotations of coredns, kube-proxy and kube-router, should get scrape=false for prometheus default setup

### Actual behavior

scrape=true

### Screenshots and logs

-

### Additional context

-

### PR DESCRIPTION
**Pull request by alessiodionisi**
## Description

This PR adds the possibility to enable or disable `prometheus.io/scrape` annotation on these system services:
- konnectivity
- coredns
- kubeproxy
- kuberouter
- calico

This change is backwards compatible because it defaults to `false`.

Example `k0s.yaml`:
```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  coredns:
    disablePrometheusScrapeAnnotation: true
  konnectivity:
    disablePrometheusScrapeAnnotation: true
  network:
    calico:
      disablePrometheusScrapeAnnotation: true
    kubeProxy:
      disablePrometheusScrapeAnnotation: true
    kuberouter:
      disablePrometheusScrapeAnnotation: true
```

Fixes #3165.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

Closes #3165.

### CODE REVIEW

**Comment by kke** [comment]
I think it's better to default booleans to false and therefore instead of `prometheusScrapeAnnotation` something like `disablePrometheusScrapeAnnotation` would be better.

**Comment by alessiodionisi** [comment]
> I think it's better to default booleans to false and therefore instead of `prometheusScrapeAnnotation` something like `disablePrometheusScrapeAnnotation` would be better.

Thanks for the feedback, I'll work on it within the next week.

**Comment by jnummelin** [comment]
@alessiodionisi Planning to still work on this?

**Comment by alessiodionisi** [comment]
@jnummelin yeah sorry, I've been really busy this time

**Comment by alessiodionisi** [comment]
Rebased

**Pull request closed without merging**
